/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import XuLy.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Database.User;

/**
 *
 * @author vinhb
 */
public class ThongTinDoiThuForm extends javax.swing.JFrame {
    private boolean isFriend;
    private User user;
    /**
     * Creates new form CompetitorInfoFrm
     */
    public ThongTinDoiThuForm(User user) {
        try {
            initComponents();
            this.user = user;
            this.setTitle("Cờ Caro Nhóm 4");
            this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
            this.setResizable(false);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setLocationRelativeTo(null);
            Avatar.setIcon(new ImageIcon("assets/avatar/"+user.getAvatar()+".jpg"));
            NickName.setText(user.getNickname());
            SoVanDaChoi.setText(""+user.getNumberOfGame());
            SoVanDaThang.setText(""+user.getNumberOfwin());
            SoVanCamHoa.setText(""+user.getNumberOfDraw());
            
            Client.socketHandle.write("check-friend,"+user.getID());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    public void checkFriend(boolean isFriend){
        this.isFriend = isFriend;
        if(isFriend){
            btn_BanBe.setIcon(new ImageIcon("assets/icon/friendship.png"));
            btn_BanBe.setToolTipText("Bạn bè");
            DaLaBanbe.setText("Bạn bè");
            
        }
        else{
            btn_BanBe.setIcon(new ImageIcon("assets/icon/add-friend.png"));
            btn_BanBe.setToolTipText("Click để gửi yêu cầu kết bạn");
            DaLaBanbe.setText("Kết bạn để chơi cùng nhau dễ dàng hơn");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_BanBe = new javax.swing.JButton();
        TenNguoiChoi = new javax.swing.JLabel();
        SoVanChoi = new javax.swing.JLabel();
        SoVanThang = new javax.swing.JLabel();
        DaLaBanbe = new javax.swing.JLabel();
        Avatar = new javax.swing.JLabel();
        NickName = new javax.swing.JLabel();
        SoVanDaChoi = new javax.swing.JLabel();
        SoVanDaThang = new javax.swing.JLabel();
        SoVanHoa = new javax.swing.JLabel();
        SoVanCamHoa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin đối thủ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btn_BanBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BanBeActionPerformed(evt);
            }
        });

        TenNguoiChoi.setText("Ingame");

        SoVanChoi.setText("Game Play");

        SoVanThang.setText("Game Win");

        DaLaBanbe.setForeground(new java.awt.Color(0, 51, 255));
        DaLaBanbe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaLaBanbe.setText("Các bạn hiện đang là bạn bè");

        NickName.setText("{nickname}");

        SoVanDaChoi.setText("{sovachoi}");

        SoVanDaThang.setText("{sovanthang}");

        SoVanHoa.setText("Game Draw");

        SoVanCamHoa.setText("{sovanhoa}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DaLaBanbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenNguoiChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoVanChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoVanThang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoVanHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SoVanDaThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SoVanDaChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NickName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoVanCamHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BanBe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BanBe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenNguoiChoi)
                    .addComponent(NickName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoVanChoi)
                    .addComponent(SoVanDaChoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoVanThang)
                    .addComponent(SoVanDaThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoVanHoa)
                    .addComponent(SoVanCamHoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(DaLaBanbe)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BanBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BanBeActionPerformed
        if(isFriend){
            JOptionPane.showMessageDialog(rootPane, "Bạn và đối thủ đang là bạn bè");
        }
        else{
            int res = JOptionPane.showConfirmDialog(rootPane, "Bạn đồng ý gửi lời mời kết bạn tới đối thủ chứ", "Xác nhận yêu cầu kết bạn", JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                try {
                    Client.socketHandle.write("make-friend,"+user.getID());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_BanBeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JLabel DaLaBanbe;
    private javax.swing.JLabel NickName;
    private javax.swing.JLabel SoVanCamHoa;
    private javax.swing.JLabel SoVanChoi;
    private javax.swing.JLabel SoVanDaChoi;
    private javax.swing.JLabel SoVanDaThang;
    private javax.swing.JLabel SoVanHoa;
    private javax.swing.JLabel SoVanThang;
    private javax.swing.JLabel TenNguoiChoi;
    private javax.swing.JButton btn_BanBe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
